version: 5.0.{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2019
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
branches:
  only:
    - master
only_commits:
  files:
    - src/
build_script:
- cmd: dotnet build ./src/EfCore.UnitOfWork.sln
test_script:
- cmd: dotnet test ./src/EfCore.UnitOfWork.UnitTests/EfCore.UnitOfWork.UnitTests.csproj
artifacts:
- path: '**/*.nupkg'
  name: Package
deploy:
- provider: NuGet
  api_key:
    secure: 0XdcR81PUAHCL0xZhiU4mNdv252OYcqaOQ1yAkC6bhyO6FwDsRqbuf82p5U0qh53
  skip_symbols: true
  on:
    branch: master
